---
- name: Run bacalhau-client.yml playbook
  import_playbook: bacalhau-client.yml

- name: Setup Bacalhau node deployment
  hosts: bacalhau_node
  become: true

  vars_files:
    - vars/settings.yml
    - vars/sec.yml

  pre_tasks:
    - name: Load in overrides if they exist
      ansible.builtin.include_vars:
        file: vars/overrides.yml
        name: overrides
      failed_when: false

    - name: Download latest production.tfvars to control machine
      get_url:
        url: "https://raw.githubusercontent.com/bacalhau-project/bacalhau/main/ops/terraform/production.tfvars"
        dest: "/tmp/bacalhau.production.tfvars"
      delegate_to: localhost
      become: false

    - name: Determine the correct Kubo (IPFS) version to install
      set_fact:
        ipfs_version: "{{ lookup('ini', 'ipfs_version type=properties file=' ~ '/tmp/bacalhau.production.tfvars') | replace('\"', '') }}"

  roles:
    - kubo
    - role: geerlingguy.docker
      when: docker_enabled and ansible_os_family not in "Darwin"

  tasks:
    - name: Install and enable Bacalhau as a service (Linux)
      when: ansible_os_family in "Debian"
      block:
        - name: Create dedicated bacalhau system user
          ansible.builtin.user:
            name: bacalhau
            comment: "Bacalhau system user"
            home: /var/lib/bacalhau
            shell: /bin/false
            system: true

        - name: Add the bacalhau user to the docker group
          ansible.builtin.user:
            name: bacalhau
            groups: docker
            append: true
          when: docker_enabled

        - name: Install bacalhau systemd service
          ansible.builtin.template:
            src: templates/bacalhau.service.j2
            dest: /etc/systemd/system/bacalhau.service
            owner: root
            group: root
            mode: "0644"

        - name: Configure bacalhau service
          ansible.builtin.template:
            src: templates/bacalhau.j2
            dest: /etc/default/bacalhau
            owner: root
            group: root
            mode: "0644"

        - name: Start and enable the Bacalhau daemon
          ansible.builtin.service:
            name: bacalhau
            state: started
            enabled: true
