---
- name: Install Bacalhau client
  hosts: bacalhau_client
  become: true

  vars_files:
    - vars/settings.yml
    - vars/sec.yml
    - vars/overrides.yml if os.path.isfile('vars/overrides.yml') else ''

  roles:
    - bacalhau
