---
- name: Install Bacalhau client
  hosts: bacalhau_client
  become: true

  vars_files:
    - vars/settings.yml
    - vars/sec.yml

  pre_tasks:
    - name: Load in overrides if they exist
      ansible.builtin.include_vars:
        file: vars/overrides.yml
        optional: true
        name: overrides

  roles:
    - bacalhau
