---
- name: Install Bacalhau client
  hosts: bacalhau_client
  become: true

  vars_files:
    - vars/settings.yml
    # Load in settings.yml again if we fail to find any overrides. This is silly but means we work whether or not the overrides file exists.
    - [ "vars/overrides.yml", "vars/settings.yml" ]
    - vars/sec.yml

  roles:
    - bacalhau
