---
- name: Deploy to the cloud
  hosts: 127.0.0.1
  become: false

  vars_files:
    - vars/settings.yml
    - vars/sec.yml

  roles:
    - cloud-deploy

- name: Deploy nodes to our freshly provisioned machines
  ansible.builtin.import_playbook: bacalhau-node.yml

# - name: Tear down DigitalOcean droplets with a specific tag
#   hosts: localhost
#   gather_facts: no
#   tasks:
#     - name: Get all droplets with the specific tag
#       community.digitalocean.digital_ocean_tag_info:
#         api_token: "{{ do_api_token }}"
#         tag_name: bacalhau_bacboot
#       register: tagged_droplets



#     - name: Print list of tagged_droplets
#       ansible.builtin.debug:
#         msg: "{{ tagged_droplets }}"

#     - name: PAUSE FOR INPUT
#       ansible.builtin.pause:
#         prompt: "Press enter to continue"

#     - name: Delete droplets with the specific tag
#       community.digitalocean.digital_ocean_droplet:
#         api_token: "{{ do_api_token }}"
#         state: absent
#         id: "{{ item.id }}"
#       loop: "{{ tagged_droplets.droplets }}"