---
bacalhau_install_dir: /usr/local/bin
use_sudo: true
use_prereleases: false
# BACALHAU_HTTP_REQUEST_CLI=curl - irrelevant to us
bacalhau_org: bacalhau-project
bacalhau_repo: bacalhau
bacalhau_cli_filename: bacalhau
# Enable support for docker
docker_enabled: true
docker_apt_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' or 'arm64' else 'amd64' }}"
# Enable support for ipfs
ipfs_enabled: true
ipfs_connect: TESTING
ipfs_install_dir: /usr/local/bin
ipfs_data_dir: ~/.ipfs
ipfs_system_user: ipfs
ipfs_system_group: ipfs
